apiVersion: v1
kind: Service
metadata:
  name: k8s-node-service
spec:
  selector: 
    app: k8s-node  
  ports:
    - protocol: TCP
      port: 80     
      nodePort: 30036
      targetPort: 3000  
  type: NodePort  